# Generated by Django 5.1.7 on 2025-07-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaction_emotional_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='emotional_trigger',
            field=models.CharField(blank=True, choices=[('Necessidade Básica', 'Necessidade Básica'), ('Planejamento/Objetivo', 'Planejamento/Objetivo'), ('Prazer/Entretenimento', 'Prazer/Entretenimento'), ('Impulso Emocional', 'Impulso Emocional'), ('Pressão Social/Status', 'Pressão Social/Status'), ('Conforto/Compulsão', 'Conforto/Compulsão'), ('Curiosidade/Exploração', 'Curiosidade/Exploração')], default='Necessidade Básica', max_length=30, null=True),
        ),
    ]
