# Generated by Django 5.1.7 on 2025-04-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
