# Generated by Django 5.1.7 on 2025-06-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_budget_month_budget_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='emotional_trigger',
            field=models.CharField(choices=[('Necessidade Básica', 'Necessicade Básica'), ('Planejamento/Objetivo', 'Planejamento/Objetivo'), ('Prazer/Entretenimento', 'Prazer/Entretenimento'), ('Impulso Emocional', 'Impulso Emocional'), ('Pressão Social/Status', 'Pressão Social/Status'), ('Conforto/Compulsão', 'Conforto/Compulsão'), ('Curiosidade/Exploração', 'Curiosidade/Exploração')], default='Necessidade Básica', max_length=30),
        ),
    ]
